/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author netha
 */
public class SplashScreen extends javax.swing.JPanel implements Runnable{

    private MainFrame parent;
    
    /**
     * Creates new form IntroWindow
     */
    public SplashScreen(MainFrame main) {
        initComponents();
        this.parent = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        loadingText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setLayout(null);
        add(loadingBar);
        loadingBar.setBounds(10, 670, 1180, 20);

        jLabel2.setText("Loading:");
        add(jLabel2);
        jLabel2.setBounds(530, 650, 50, 16);

        loadingText.setText("Checking Requirements");
        add(loadingText);
        loadingText.setBounds(580, 650, 190, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("General Accounting Ledger");
        add(jLabel3);
        jLabel3.setBounds(0, 400, 1200, 67);

        jLabel1.setFont(new java.awt.Font("BIZ UDGothic", 0, 150)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("G.A.L.");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 650);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel loadingText;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        
        try {
            String text = "Checking Requirements";
            for (int i=0; i<=100; i++) {
                Thread.sleep(80);
                final int progress = i;
                
                switch (progress) {
                    case 50 -> text = "Loading Modules";
                    case 60 -> text = "Compiling Modules";
                    case 80 -> text = "Retrieving Data";
                    case 90 -> text = "Loading Data";
                    case 100 -> text = "Done";
                }
                this.loadingText.setText(text);
                
                SwingUtilities.invokeLater(() -> this.loadingBar.setValue(progress));
            }
            
            this.parent.switchFrames(this, this.parent.ledgerFrame);
        } catch (InterruptedException ex) {
            System.out.println("error in loading Screen");
        }
    }
}
